#  ANOVA

In statistics, **Analysis of Variance (ANOVA)** is also used to analyze the differences among group means. The difference between t-test and ANOVA is the former is ued to compare two groups whereas the latter is used to compare three or more groups. [Read more about the difference between t-test and ANOVA](http://b.link/anova24).

From the ANOVA test, you receive two numbers. The first number is called the **F-value** which indicates whether your null-hypothesis can be rejected. The critical F-value that rejects the null-hypothesis varies according to the number of total subjects and the number of subject groups in your experiment. In [this table](http://b.link/eda14) you can find the critical values of the F distribution. **If you are confused by the massive F-distribution table, don't worry. Skip F-value for now and study it at a later time. In this challenge you only need to look at the p-value.**

The p-value is another number yielded by ANOVA which already takes the number of total subjects and the number of experiment groups into consideration. **Typically if your p-value is less than 0.05, you can declare the null-hypothesis is rejected.**

In this challenge, we want to understand whether there are significant differences among various types of pokemons' `Total` value, i.e. Grass vs Poison vs Fire vs Dragon... There are many types of pokemons which makes it a perfect use case for ANOVA. Use Ironhack's database to load the pokemon data (db: pokemon, table: pokemon_stats).

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import scipy.stats as st

In [3]:
# Load the data:
data = pd.read_csv('pokemon.csv')
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

**To achieve our goal, we use three steps:**

1. **Extract the unique values of the pokemon types.**

1. **Select dataframes for each unique pokemon type.**

1. **Conduct ANOVA analysis across the pokemon types.**

#### First let's obtain the unique values of the pokemon types. These values should be extracted from Type 1 and Type 2 aggregated. Assign the unique values to a variable called `unique_types`.

*Hint: the correct number of unique types is 19 including `NaN`. You can disregard `NaN` in next step.*

In [4]:
def combo(value):
    type1 = value['Type 1'];
    type2 = value['Type 2']
    if str(type2) == 'nan':
        return type1
    else:
        return type1 +'-'+ type2
    
data['Combo Types'] = data.apply(combo, axis=1)
#data['Combo Types'] = data['Combo Types'].str.split('-')

In [ ]:
#unique_types = []
#for x in data['Type 1']:
#    if x not in unique_types:
#        unique_types.append(x)
#
#len(unique_types)

In [ ]:
#We concluded that it makes more sense to look at all combos instead of the single types

In [5]:
unique_types_combo = []
for x in data['Combo Types']:
    if x not in unique_types_combo:
        unique_types_combo.append(x)

unique_types_combo

['Grass-Poison',
 'Fire',
 'Fire-Flying',
 'Fire-Dragon',
 'Water',
 'Bug',
 'Bug-Flying',
 'Bug-Poison',
 'Normal-Flying',
 'Normal',
 'Poison',
 'Electric',
 'Ground',
 'Poison-Ground',
 'Fairy',
 'Normal-Fairy',
 'Poison-Flying',
 'Bug-Grass',
 'Fighting',
 'Water-Fighting',
 'Psychic',
 'Water-Poison',
 'Rock-Ground',
 'Water-Psychic',
 'Electric-Steel',
 'Water-Ice',
 'Ghost-Poison',
 'Grass-Psychic',
 'Ground-Rock',
 'Grass',
 'Psychic-Fairy',
 'Ice-Psychic',
 'Water-Flying',
 'Water-Dark',
 'Rock-Water',
 'Rock-Flying',
 'Ice-Flying',
 'Electric-Flying',
 'Dragon',
 'Dragon-Flying',
 'Psychic-Fighting',
 'Water-Electric',
 'Fairy-Flying',
 'Psychic-Flying',
 'Electric-Dragon',
 'Water-Fairy',
 'Rock',
 'Grass-Flying',
 'Water-Ground',
 'Dark',
 'Dark-Flying',
 'Ghost',
 'Normal-Psychic',
 'Bug-Steel',
 'Ground-Flying',
 'Steel-Ground',
 'Bug-Rock',
 'Bug-Fighting',
 'Dark-Ice',
 'Fire-Rock',
 'Ice-Ground',
 'Water-Rock',
 'Steel-Flying',
 'Dark-Fire',
 'Water-Dragon',
 'Rock-Dark',
 'Psychic-Grass',
 'Grass-Dragon',
 'Fire-Fighting',
 'Water-Grass',
 'Grass-Dark',
 'Bug-Water',
 'Grass-Fighting',
 'Bug-Ground',
 'Bug-Ghost',
 'Dark-Ghost',
 'Steel-Fairy',
 'Steel-Rock',
 'Steel',
 'Fighting-Psychic',
 'Fire-Ground',
 'Ground-Dragon',
 'Dragon-Fairy',
 'Rock-Psychic',
 'Ground-Psychic',
 'Rock-Grass',
 'Rock-Bug',
 'Ice',
 'Ice-Water',
 'Steel-Psychic',
 'Dragon-Psychic',
 'Ground-Fire',
 'Grass-Ground',
 'Water-Steel',
 'Normal-Water',
 'Rock-Steel',
 'Ghost-Flying',
 'Normal-Fighting',
 'Poison-Dark',
 'Ghost-Dark',
 'Dragon-Ground',
 'Fighting-Steel',
 'Poison-Bug',
 'Poison-Fighting',
 'Grass-Ice',
 'Ice-Ghost',
 'Electric-Ghost',
 'Electric-Fire',
 'Electric-Water',
 'Electric-Ice',
 'Electric-Grass',
 'Steel-Dragon',
 'Fire-Steel',
 'Ghost-Dragon',
 'Psychic-Fire',
 'Ground-Steel',
 'Grass-Fairy',
 'Ground-Dark',
 'Fire-Psychic',
 'Dark-Fighting',
 'Normal-Grass',
 'Water-Ghost',
 'Bug-Electric',
 'Grass-Steel',
 'Ghost-Fire',
 'Ground-Electric',
 'Ground-Ghost',
 'Dark-Steel',
 'Dark-Dragon',
 'Bug-Fire',
 'Steel-Fighting',
 'Rock-Fighting',
 'Flying',
 'Dragon-Fire',
 'Dragon-Electric',
 'Dragon-Ice',
 'Normal-Ground',
 'Fire-Normal',
 'Fighting-Dark',
 'Steel-Ghost',
 'Dark-Psychic',
 'Poison-Water',
 'Poison-Dragon',
 'Electric-Normal',
 'Rock-Dragon',
 'Rock-Ice',
 'Fighting-Flying',
 'Electric-Fairy',
 'Rock-Fairy',
 'Ghost-Grass',
 'Flying-Dragon',
 'Psychic-Ghost',
 'Psychic-Dark',
 'Fire-Water']

#### Second we will create a list named `pokemon_totals` to contain the `Total` values of each unique type of pokemons.

Why we use a list instead of a dictionary to store the pokemon `Total`? It's because ANOVA only tells us whether there is a significant difference of the group means but does not tell which group(s) are significantly different. Therefore, we don't need know which `Total` belongs to which pokemon type.

*Hints:*

* Loop through `unique_types` and append the selected type's `Total` to `pokemon_groups`.
* Skip the `NaN` value in `unique_types`. `NaN` is a `float` variable which you can find out by using `type()`. The valid pokemon type values are all of the `str` type.
* At the end, the length of your `pokemon_totals` should be 18.

In [6]:
len(data)

800

In [7]:
data['Total']

0      318
1      405
2      525
3      625
4      309
      ...
795    600
796    700
797    600
798    680
799    600
Name: Total, Length: 800, dtype: int64

In [ ]:
#pokemon_totals=[]
#for x in unique_types_combo:
#    total=0
#    for i in range(0,len(data)):
#        #print(i)
#        if data['Combo Types'][i]==x:
#            total+=data['Total'][i]
#    pokemon_totals.append(total)
#            
#    
#pokemon_totals

In [8]:

list_of_totals=[]

for x in unique_types_combo:
    pokemon_totals=[]
    for i in range(0,len(data)):
        if data['Combo Types'][i]==x:
            pokemon_totals.append(data['Total'][i])
    list_of_totals.append(pokemon_totals)

            
    
list_of_totals

[[318, 405, 525, 625, 320, 395, 490, 300, 390, 490, 400, 280, 515, 294, 464],
 [309,
  405,
  299,
  505,
  350,
  555,
  410,
  500,
  495,
  525,
  309,
  405,
  534,
  250,
  365,
  580,
  310,
  470,
  309,
  540,
  308,
  316,
  498,
  315,
  480,
  484,
  307,
  409],
 [534, 634, 580, 680, 382, 499],
 [634],
 [314,
  405,
  530,
  630,
  320,
  500,
  300,
  385,
  325,
  305,
  325,
  475,
  295,
  440,
  320,
  450,
  340,
  200,
  525,
  314,
  405,
  530,
  500,
  300,
  480,
  580,
  310,
  400,
  500,
  308,
  200,
  540,
  345,
  485,
  485,
  330,
  670,
  770,
  314,
  405,
  330,
  495,
  325,
  330,
  460,
  480,
  600,
  308,
  413,
  528,
  316,
  498,
  294,
  460,
  470,
  314,
  405,
  330,
  500],
 [195,
  205,
  500,
  290,
  195,
  205,
  205,
  400,
  400,
  194,
  384,
  224,
  315,
  305,
  495,
  200,
  213],
 [395, 500, 600, 265, 390, 390, 395, 414, 456, 424, 244, 474, 515, 411],
 [195, 205, 395, 495, 305, 450, 250, 390, 385, 260, 360, 485],
 [251,
  349,
  479,
  579,
  262,
  442,
  352,
  310,
  460,
  262,
  442,
  270,
  430,
  310,
  245,
  340,
  485,
  411,
  264,
  358,
  488,
  350,
  510,
  278],
 [253,
  413,
  290,
  440,
  385,
  450,
  490,
  590,
  490,
  288,
  325,
  395,
  540,
  215,
  415,
  360,
  415,
  330,
  500,
  515,
  465,
  250,
  490,
  540,
  240,
  420,
  280,
  440,
  670,
  240,
  360,
  490,
  260,
  380,
  360,
  458,
  420,
  440,
  250,
  482,
  350,
  480,
  310,
  452,
  220,
  390,
  515,
  535,
  670,
  720,
  255,
  420,
  275,
  370,
  500,
  445,
  300,
  470,
  490,
  237,
  472],
 [288, 438, 275, 365, 273, 365, 325, 500, 340, 490, 302, 467, 458, 329, 474],
 [320,
  485,
  330,
  480,
  490,
  525,
  205,
  280,
  365,
  510,
  360,
  580,
  295,
  475,
  575,
  405,
  405,
  263,
  363,
  523,
  405,
  540,
  295,
  497,
  275,
  405,
  515],
 [300, 450, 265, 405, 320, 425, 330, 500, 290, 670, 330, 525, 328],
 [505, 505],
 [323, 483, 218, 245, 300, 450, 303, 371, 552, 341, 462, 341, 480, 525, 680],
 [270, 435, 210, 190, 545],
 [245, 455, 535],
 [285, 405, 424, 310, 380, 500],
 [305,
  455,
  305,
  405,
  505,
  455,
  455,
  210,
  455,
  237,
  474,
  285,
  305,
  405,
  505,
  465,
  465,
  350,
  510,
  348],
 [510, 580, 580],
 [310,
  400,
  500,
  590,
  328,
  483,
  680,
  780,
  600,
  525,
  336,
  405,
  330,
  470,
  425,
  260,
  600,
  600,
  600,
  600,
  285,
  580,
  580,
  580,
  600,
  292,
  487,
  290,
  390,
  490,
  290,
  370,
  490,
  335,
  485,
  355,
  466,
  466],
 [335, 515, 430],
 [300, 390, 495, 385, 300, 410],
 [315, 490, 590, 520, 490],
 [325, 465, 535],
 [475, 525, 535],
 [310, 405, 500, 600],
 [325, 520],
 [345, 485, 535],
 [435,
  318,
  405,
  525,
  490,
  180,
  425,
  310,
  405,
  530,
  220,
  295,
  335,
  318,
  405,
  275,
  450,
  454,
  535,
  525,
  600,
  308,
  413,
  528,
  316,
  498,
  280,
  480,
  461,
  313,
  405,
  350,
  531],
 [460, 198, 278, 518, 618, 310],
 [455, 305],
 [540, 465, 270, 430, 345, 305, 473],
 [640, 305, 460, 560, 468, 530],
 [355, 495, 355, 495, 306, 500],
 [515, 615, 401, 567],
 [580, 330],
 [580, 520, 428, 580, 580],
 [300, 420, 300, 420, 320, 410, 540, 485, 300, 452, 600],
 [600, 490, 600, 700, 680, 780],
 [780, 518, 618],
 [330, 460],
 [405, 545],
 [320, 470, 680, 313, 425, 490],
 [610],
 [250, 420],
 [410, 375, 580, 350, 495, 290, 280, 390, 515],
 [250, 340, 460, 460, 600],
 [210, 430, 405, 535, 635, 288, 468, 475, 384, 509],
 [525, 220, 420, 465, 565, 600, 281, 446, 330, 510],
 [405, 505, 370, 510, 680],
 [435, 295, 455, 555, 295, 455, 495, 525, 303, 483],
 [455, 600],
 [465, 500, 600, 424, 495, 484, 600],
 [430, 510, 600, 600],
 [510, 610],
 [505, 325, 475],
 [500, 600],
 [430, 510],
 [410],
 [250, 450, 530],
 [380, 485, 355, 495],
 [465],
 [330, 500, 600],
 [540, 680],
 [600, 700],
 [600],
 [630],
 [405, 530, 630, 405, 534, 418, 528],
 [220, 340, 480],
 [340, 480, 475],
 [269],
 [460, 580, 530],
 [266, 424],
 [236],
 [380, 480],
 [380, 480, 470],
 [330, 430, 530],
 [630, 580, 300, 440, 520],
 [280, 410, 510],
 [305, 460, 560],
 [340, 520],
 [590],
 [440, 440],
 [300, 500],
 [355, 495],
 [355, 495],
 [300, 480, 580, 580, 525, 305, 395, 535, 305, 485, 485, 304, 514],
 [290, 410, 530],
 [300, 420, 600, 700, 600, 300, 500],
 [600, 700, 600, 700],
 [770],
 [525],
 [530],
 [410],
 [350, 495, 525],
 [348, 498],
 [580, 600],
 [329, 479, 500],
 [485],
 [300, 410, 600, 700, 600],
 [525, 625],
 [330],
 [300, 490],
 [334, 494, 594],
 [480],
 [440],
 [520],
 [520],
 [520],
 [520],
 [680],
 [600],
 [680, 680],
 [600],
 [508],
 [280, 480],
 [292, 351, 519],
 [540, 534],
 [348, 488],
 [335, 475],
 [335, 480],
 [319, 472],
 [305, 489],
 [275, 370, 520],
 [471],
 [303, 483],
 [340, 490],
 [300, 420, 600],
 [360, 550],
 [580],
 [580],
 [580, 580],
 [680],
 [680],
 [660, 700, 700],
 [423],
 [369, 507],
 [495],
 [325, 448, 520, 520],
 [288, 482],
 [320],
 [494],
 [289, 481],
 [362, 521],
 [362, 521],
 [500],
 [431],
 [500, 600, 700],
 [309, 474, 335, 335, 335, 335, 494, 494, 494, 494],
 [245, 535],
 [600],
 [680],
 [600]]

In [ ]:
#poke_data={'type': pokemon_group, 'totals': pokemon_totals}
#poke_data=pd.DataFrame(poke_data)
#poke_data

In [ ]:
#new = {'type': unique_types_combo, 'totals': pokemon_totals}
#new = pd.DataFrame(new)
#new

In [ ]:
#len(pokemon_totals)

In [ ]:
#data[data['Combo Types']=='Grass-Poison']['Total'].sum()

#### Now we run ANOVA test on `pokemon_totals`.

*Hints:*

* To conduct ANOVA, you can use `scipy.stats.f_oneway()`. Here's the [reference](http://b.link/scipy44).

* What if `f_oneway` throws an error because it does not accept `pokemon_totals` as a list? The trick is to add a `*` in front of `pokemon_totals`, e.g. `stats.f_oneway(*pokemon_groups)`. This trick breaks the list and supplies each list item as a parameter for `f_oneway`.

In [9]:
st.f_oneway(*list_of_totals)

F_onewayResult(statistic=2.0538240752912196, pvalue=5.865343391415285e-10)

#### Interpret the ANOVA test result. Is the difference significant?

In [ ]:
# H0 for ANOVA is always that the means of the various groups are the same
# H1 is that they are not the same

In [ ]:
# This means with the very low p value, that we have to reject the H0 hypothesis, so we have reason to believe, that the means
# of the total stats of the different pokemon is significantly different.